{% set name = "ssm-simulators" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ssm_simulators-{{ version }}.tar.gz
  sha256: fd80e72dc86a1bd702fb5453cf78c03da59b6e026201b2cc0f5fe8f8fc9957a3

build:
  skip: true  # [py<=39 or py>=312 or py2k]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cython
  host:
    - python
    - setuptools
    - wheel
    - cython
    - numpy
    - pip
  run:
    - python
    - numpy >=1.26.4,<2.0
    - scipy >=1.6.3
    - pandas >=1.0.0
    - scikit-learn >=0.24.0
    - psutil >=5.0.0
    - pathos >= 0.3.0

test:
  imports:
    - ssms
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/ssm-simulators
  summary: SSMS is a package collecting simulators and training data generators for a bunch of generative models of interest in the cognitive science / neuroscience and approximate bayesian computation communities
  dev_url: https://github.com/AlexanderFengler/ssm-simulators
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AlexanderFengler
    - digicosmos86
